CREATE DATABASE IF NOT EXISTS wine;

USE wine;

DROP TABLE IF EXISTS red;

CREATE TABLE red (
id INT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(45) NOT NULL,
country VARCHAR(45) NOT NULL,
region VARCHAR(45) NOT NULL,
winery VARCHAR(45) NOT NULL,
rating FLOAT NOT NULL,
number_of_ratings INT NOT NULL,
price FLOAT NOT NULL,
year VARCHAR(10)
);

DROP TABLE IF EXISTS rose;

CREATE TABLE rose (
id INT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(45) NOT NULL,
country VARCHAR(45) NOT NULL,
region VARCHAR(45) NOT NULL,
winery VARCHAR(45) NOT NULL,
rating FLOAT NOT NULL,
number_of_ratings INT NOT NULL,
price FLOAT NOT NULL,
year VARCHAR(10)
);

DROP TABLE IF EXISTS sparkling;

CREATE TABLE sparkling (
id INT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(45) NOT NULL,
country VARCHAR(45) NOT NULL,
region VARCHAR(45) NOT NULL,
winery VARCHAR(45) NOT NULL,
rating FLOAT NOT NULL,
number_of_ratings INT NOT NULL,
price FLOAT NOT NULL,
year VARCHAR(10)
);

DROP TABLE IF EXISTS white;

CREATE TABLE white (
id INT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(45) NOT NULL,
country VARCHAR(45) NOT NULL,
region VARCHAR(45) NOT NULL,
winery VARCHAR(45) NOT NULL,
rating FLOAT NOT NULL,
number_of_ratings INT NOT NULL,
price FLOAT NOT NULL,
year VARCHAR(10)
);